# Generated by Django 4.0.3 on 2022-03-18 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_course_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='url',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
